# Generated by Django 3.0.5 on 2020-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENo', models.IntegerField()),
                ('EName', models.CharField(max_length=30)),
                ('ESal', models.IntegerField()),
                ('EAddr', models.CharField(max_length=50)),
            ],
        ),
    ]
