# Generated by Django 3.0.8 on 2020-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('EName', models.CharField(max_length=100)),
                ('ESalary', models.FloatField()),
                ('Eloc', models.CharField(max_length=100)),
                ('EPos', models.CharField(max_length=100)),
            ],
        ),
    ]
