# Generated by Django 3.0.6 on 2020-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('EName', models.CharField(max_length=30)),
                ('ESal', models.FloatField()),
                ('Eaddress', models.CharField(max_length=100)),
                ('Eemail', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
