# Generated by Django 3.0.8 on 2020-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name1', models.CharField(max_length=50, verbose_name='Student Name')),
                ('fathers_name', models.CharField(max_length=60, verbose_name="Father's Name")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=30, verbose_name='Year')),
                ('fee_type', models.CharField(choices=[('Fine', 'Fine'), ('Fees', 'Fees'), ('Other', 'Other')], max_length=30, verbose_name='Type')),
                ('fees_amount', models.FloatField(max_length=10, verbose_name='Amount')),
                ('balance', models.FloatField(max_length=10, verbose_name='Balance')),
                ('dos', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Fees Detail',
                'db_table': 'Fees Detail',
            },
        ),
        migrations.CreateModel(
            name='StudentDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('fathers_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30, verbose_name='Gender')),
                ('course', models.CharField(max_length=30, verbose_name='Course')),
                ('branch', models.CharField(max_length=30, verbose_name='Branch')),
                ('contact1', models.IntegerField(unique=True, verbose_name="Parent's contact")),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('doj', models.DateField(verbose_name='Date of Admission')),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=30, verbose_name='Year')),
                ('actual_fees', models.FloatField(max_length=20, verbose_name='Actual Amount')),
                ('concession', models.FloatField(max_length=30, verbose_name='Concession')),
                ('balance', models.FloatField(max_length=20, verbose_name='Balance')),
                ('currently_paid', models.FloatField(max_length=20, verbose_name='Currently Paid')),
                ('net_pay', models.FloatField(max_length=20, verbose_name='Net Payable')),
            ],
            options={
                'verbose_name': 'Student Database',
                'db_table': 'Student database',
            },
        ),
    ]
